# Site settings
author: Andrew Thomas
title: Another Tech Blog
email: blog@at-dot.net
description: Like we need another blog
baseurl: ""
url: "http://blog.at-dot.net/"
gravatar_url: http://www.gravatar.com/avatar/ed0b6712d7b2d6725ea107f2ddecc138.png
subscribe_rss: http://blog.at-dot.net/atom.xml

# Github
github_user: athomas4219
github_repo_url: https://github.com/athomas4219/

# Twitter
twitter_user: segfault4219
twitter_tweet_button: true

# Disqus
disqus_short_name: andrewthomasblog
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-46642002-1

# Build settings
markdown: kramdown
permalink: /archive/:year/:month/:day/:title/
paginate: 10
paginate_path: "page/:num"
category_dir: categories

plugins:
  - jekyll-sitemap
  - jekyll-paginate
